In [2]:
library(tidyverse)
library(edgeR)
library(ggrastr)
library(gridExtra)
library(RColorBrewer)
library(patchwork)
theme_set(theme_bw())

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: limma


Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine

In [1]:
# Differential Accessibility Region (DAR) Analysis with Custom Normalization
#
# This function performs differential accessibility analysis using edgeR,
# incorporating custom normalization based on user-supplied effective library sizes 
# The specific use case is for normalizing ATAC-seq using counts from promoter regions of genes that are invariantly expressed in control and BAF-inhibited samples.
#
# Inputs are:
#     data,  A matrix of raw counts (peaks x samples).
#     coldata, A data frame containing sample metadata. Must include:
#      `Condition`: Factor or character vector indicating experimental groups (e.g., control, treatment).
#      `sizes`: Numeric vector of effective library sizes (i.e., sum of counts at invariant promoters)
#
# This function returns a data frame with differential test results for each region, including logFC, p-values, and FDR
# As well as a classification of each element as gaining ("up"), losing ("down"), or not changing ("nc") in accessibility
# Based on FDR and logFC cutoffs of 0.05 and log2(1.5), respectively

dar <- function(data, coldata) {
    library(edgeR)
  
  # Create DGEList object with counts and group information
    dge <- DGEList(counts = data, group = coldata$Condition)
  
  # Override default library size with effective library sizes from control regions
    dge$samples$lib.size <- coldata$sizes
  
  # Set normalization factors to 1 (i.e., use lib.size as-is with no further scaling)
    dge$samples$norm.factors <- rep(1, nrow(coldata))
  
  # Create design matrix for comparison (model without intercept, group-specific columns)
    design <- model.matrix(~0 + group, data = dge$samples)
    colnames(design) <- levels(dge$samples$group)  # optional: label columns by condition names
  
  # Estimate dispersion 
    dge <- estimateDisp(dge, design)
  
  # Fit generalized linear model (GLM) 
    dge_fit <- glmQLFit(dge, design)
  
  # Conduct differential test (treatment vs control)
    diff <- glmQLFTest(dge_fit, contrast = c(1, -1))
  
  # Return all regions without sorting; include logFC, p-value, FDR, etc.
    res <- topTags(diff, n = Inf, sort.by = "none")$table 
  # Add column categorizing peaks as gaining, losing, or not changing accessibility
    res <- res %>% mutate(
                    change = case_when(FDR < 0.05 & logFC > log2(2) ~ "up",
                                       FDR < 0.05 & logFC < -log2(2) ~ "down",
                                       TRUE ~ "nc"))
  return(res)
}

# This function implements the dar() function separately for TSS-distal and TSS-proximal peaks. 
# In addition to the data and coldata params required by dar(), this function additionall requires
# a 'rowdata' object (should contain minimally genomic coordinates and TSS proximity for each row)

# This function returns a list object where the first element is the table of results from DAR analysis, 
# And the second is a reformatted rowdata object (rows reordered so that they match the results table)

dar_splitTSS <- function(data, coldata, rowdata){ 
    #Use row metadata to split counts matrix into TSS-proximal and dista
    #Run DAR analysis separately on each
    res_tss <- dar(data=data[rowdata$TSS==TRUE,], coldata)
    res_nontss <- dar(data=data[rowdata$TSS==FALSE,], coldata)

    #combine TSS and nonTSS DAR results
    res <- rbind(res_tss, res_nontss) %>% mutate(BAFdep=case_when(change == "down" ~ TRUE, TRUE ~ FALSE)) #add column that binarizes peaks into BAF-dependent (significant accessibility loss) and independent
    #reorder rowdata
    rowdata <- rbind(rowdata[rowdata$TSS==TRUE,], rowdata[rowdata$TSS==FALSE,])
    return(list("results"=res, "row_meta"=rowdata))
}

In [2]:
#read in counts data
countmat <- read.delim("/mnt/disk/home/agulka/manuscripts/BAF_stimulus_CellGenomics/inputs/countmat/H1/H1_consensus_filt.tsv", header=F, sep='\t')
#read in row metadata
row_meta <- read.delim("/mnt/disk/home/agulka/manuscripts/BAF_stimulus_CellGenomics/inputs/bed/ATAC_peaks/H1/filtered/H1_consensus_filt_annot.tsv", sep='\t')

#read in column metadata
col_meta <- data.frame(Condition=c(rep("C_Control", 3), rep("B_ACBI1", 3), rep("A_A4-KD",3)), rep=rep(1:3,3))

#filter to only include counts (exclude genomic coordinates)
counts <- countmat[,5:13]

In [63]:
#read in control counts (reads over promoters of genes invariantly expressed in BAFinh 6h/10µM vs DMSO
control_mat <- read.delim("/mnt/disk/home/agulka/manuscripts/BAF_stimulus_CellGenomics/inputs/countmat/H1/H1_invariant_promoters.tsv", header=F, sep='\t')
#calculate effective library sizes for normalization (sum of counts over each control region set)
lib_sizes <- colSums(control_mat[,5:13])

#add library sizes to column metadata
col_meta <- col_meta %>% mutate(sizes=lib_sizes)

In [64]:
#DAR analysis
dar_ACBI1 <- dar_splitTSS(data=counts[,col_meta$Condition %in% c("C_Control", "B_ACBI1")], coldata=col_meta[col_meta$Condition %in% c("C_Control", "B_ACBI1"),], row_meta) 
dar_A4KD <- dar_splitTSS(data=counts[,col_meta$Condition %in% c("C_Control", "A_A4-KD")], coldata=col_meta[col_meta$Condition %in% c("C_Control", "A_A4-KD"),], row_meta)

In [68]:
write.table(cbind(dar_ACBI1$row_meta[,1:3],dar_ACBI1$results %>% mutate(BAFdep=case_when(change == "down" ~ TRUE, TRUE ~ FALSE))), "H1_ACBI1_DAR.tsv", quote=FALSE, row.names=FALSE, sep='\t')
write.table(cbind(dar_A4KD$row_meta[,1:3],dar_A4KD$results %>% mutate(BAFdep=case_when(change == "down" ~ TRUE, TRUE ~ FALSE))), "H1_SMARCA4-KD_DAR.tsv", quote=FALSE, row.names=FALSE, sep='\t')

In [69]:
head(dar_ACBI1$results)

   logFC       logCPM   F         PValue      FDR        change BAFdep
1   0.22115269 6.843794 9.1672526 0.003054157 0.01123155 nc     FALSE
4   0.05683820 4.390230 0.1163496 0.733662755 0.82031053 nc     FALSE
6   0.07363391 7.351576 1.4146585 0.236783637 0.36629658 nc     FALSE
10 -0.03020429 5.299191 0.0571797 0.811444555 0.87536402 nc     FALSE
11  0.19292781 5.677676 3.0052991 0.085726611 0.16937453 nc     FALSE
12 -0.05247901 7.076201 0.5576994 0.456743310 0.59271777 nc     FALSE

In [3]:
row_meta

       seqnames start    end      width strand TSS   H3K4me3 H3K4me1 H3K27ac
1      chr1      778366   779299   934  *       TRUE  TRUE   FALSE    TRUE
2      chr1      797430   797966   537  *      FALSE FALSE   FALSE   FALSE
3      chr1      804756   805016   261  *      FALSE FALSE   FALSE   FALSE
4      chr1      817333   818369  1037  *       TRUE FALSE   FALSE   FALSE
5      chr1      818971   819172   202  *      FALSE FALSE   FALSE   FALSE
6      chr1      826738   828129  1392  *       TRUE  TRUE   FALSE    TRUE
7      chr1      844547   844987   441  *      FALSE FALSE    TRUE   FALSE
8      chr1      845693   846001   309  *      FALSE  TRUE   FALSE   FALSE
9      chr1      856704   857041   338  *      FALSE FALSE   FALSE   FALSE
10     chr1      858030   859066  1037  *       TRUE FALSE    TRUE   FALSE
11     chr1      869575   870303   729  *       TRUE  TRUE   FALSE   FALSE
12     chr1      903765   905579  1815  *       TRUE  TRUE    TRUE   FALSE
13     chr1      912656   913711  1056  *       TRUE FALSE   FALSE   FALSE
14     chr1      920825   921423   599  *       TRUE  TRUE    TRUE   FALSE
15     chr1      923604   925340  1737  *       TRUE  TRUE    TRUE   FALSE
16     chr1      925517   925992   476  *       TRUE  TRUE    TRUE   FALSE
17     chr1      932234   932626   393  *      FALSE FALSE   FALSE   FALSE
18     chr1      933656   934005   350  *      FALSE FALSE   FALSE   FALSE
19     chr1      935708   936257   550  *      FALSE  TRUE    TRUE   FALSE
20     chr1      939153   939402   250  *       TRUE FALSE    TRUE   FALSE
21     chr1      940202   942884  2683  *       TRUE  TRUE    TRUE   FALSE
22     chr1      951140   952144  1005  *      FALSE FALSE   FALSE   FALSE
23     chr1      959006   961623  2618  *       TRUE  TRUE    TRUE   FALSE
24     chr1      966085   967367  1283  *       TRUE  TRUE    TRUE   FALSE
25     chr1      970317   970973   657  *       TRUE  TRUE    TRUE   FALSE
26     chr1      975871   976706   836  *       TRUE  TRUE    TRUE   FALSE
27     chr1      978524   979093   570  *      FALSE FALSE   FALSE   FALSE
28     chr1      983874   984617   744  *      FALSE FALSE   FALSE   FALSE
29     chr1      998457  1000993  2537  *       TRUE  TRUE    TRUE    TRUE
30     chr1     1001398  1002121   724  *       TRUE  TRUE    TRUE   FALSE
⋮      ⋮        ⋮        ⋮        ⋮     ⋮      ⋮     ⋮       ⋮       ⋮
177052 chrY     18459216 18459447  232  *      FALSE FALSE   FALSE   FALSE
177053 chrY     18565967 18566213  247  *      FALSE FALSE   FALSE   FALSE
177054 chrY     18608278 18608555  278  *      FALSE FALSE   FALSE   FALSE
177055 chrY     18629702 18630403  702  *      FALSE FALSE   FALSE   FALSE
177056 chrY     18669904 18670108  205  *      FALSE FALSE   FALSE   FALSE
177057 chrY     18689770 18690701  932  *      FALSE FALSE   FALSE   FALSE
177058 chrY     18711848 18712109  262  *      FALSE FALSE   FALSE   FALSE
177059 chrY     18754197 18754427  231  *      FALSE FALSE   FALSE   FALSE
177060 chrY     18860940 18861169  230  *      FALSE FALSE   FALSE   FALSE
177061 chrY     18884721 18885132  412  *      FALSE FALSE   FALSE    TRUE
177062 chrY     18992661 18993146  486  *       TRUE FALSE   FALSE   FALSE
177063 chrY     19006333 19006547  215  *      FALSE  TRUE   FALSE   FALSE
177064 chrY     19015915 19016190  276  *      FALSE FALSE   FALSE   FALSE
177065 chrY     19023995 19024208  214  *      FALSE  TRUE   FALSE    TRUE
177066 chrY     19024305 19024764  460  *      FALSE  TRUE   FALSE    TRUE
177067 chrY     19042179 19043673 1495  *      FALSE  TRUE   FALSE    TRUE
177068 chrY     19075517 19076343  827  *       TRUE  TRUE   FALSE    TRUE
177069 chrY     19076743 19077539  797  *       TRUE FALSE   FALSE   FALSE
177070 chrY     19142117 19142574  458  *      FALSE  TRUE   FALSE   FALSE
177071 chrY     19146139 19146890  752  *      FALSE  TRUE   FALSE    TRUE
177072 chrY     19291005 19291235  231  *      FALSE FALSE   FALSE   FALSE
177073 chrY     19427824 19428551  728  *      FALSE  TRUE   FALSE    TRUE
177074 chrY     19433100 19433363  264  *      FALSE FALSE   FALSE   FALSE
177075 chrY     19503264 19503483  220  *       TRUE FALSE   FALSE   FALSE
177076 chrY     19541608 19541979  372  *      FALSE FALSE   FALSE   FALSE
177077 chrY     19549914 19550716  803  *      FALSE  TRUE    TRUE   FALSE
177078 chrY     19566912 19568176 1265  *       TRUE  TRUE   FALSE    TRUE
177079 chrY     19744345 19745287  943  *       TRUE  TRUE   FALSE    TRUE
177080 chrY     20575442 20576230  789  *       TRUE  TRUE   FALSE    TRUE
177081 chrY     26670538 26671554 1017  *      FALSE FALSE   FALSE   FALSE
       H3K27me3 CTCF  type                inDMSO inACBI1 inACBI1.1 ID
1      FALSE     TRUE prom                 TRUE   TRUE    TRUE      1
2      FALSE    FALSE other_nonTSS         TRUE   TRUE   FALSE      2
3      FALSE    FALSE other_nonTSS         TRUE  FALSE   FALSE      3
4      FALSE    FALSE other_TSS            TRUE   TRUE    TRUE      4
5      FALSE    FALSE other_nonTSS        FALSE   TRUE   FALSE      5
6      FALSE    FALSE prom                 TRUE   TRUE    TRUE      6
7      FALSE    FALSE poised_enh           TRUE   TRUE    TRUE      7
8      FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE      8
9      FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE      9
10     FALSE    FALSE other_TSS            TRUE   TRUE    TRUE     10
11     FALSE     TRUE prom                 TRUE   TRUE    TRUE     11
12      TRUE     TRUE prom                 TRUE   TRUE    TRUE     12
13      TRUE     TRUE other_TSS            TRUE   TRUE    TRUE     13
14      TRUE     TRUE prom                 TRUE   TRUE    TRUE     14
15      TRUE    FALSE prom                 TRUE   TRUE    TRUE     15
16      TRUE    FALSE prom                 TRUE   TRUE    TRUE     16
17      TRUE    FALSE other_nonTSS        FALSE  FALSE    TRUE     17
18      TRUE    FALSE other_nonTSS         TRUE   TRUE   FALSE     18
19      TRUE    FALSE poised_enh_H3K27me3  TRUE  FALSE    TRUE     19
20      TRUE     TRUE other_TSS            TRUE   TRUE    TRUE     20
21      TRUE    FALSE prom                 TRUE   TRUE    TRUE     21
22     FALSE     TRUE CTCF_only            TRUE   TRUE    TRUE     22
23      TRUE    FALSE prom                 TRUE   TRUE    TRUE     23
24      TRUE    FALSE prom                 TRUE   TRUE    TRUE     24
25      TRUE    FALSE prom                 TRUE   TRUE    TRUE     25
26     FALSE     TRUE prom                 TRUE   TRUE    TRUE     26
27     FALSE    FALSE other_nonTSS        FALSE   TRUE   FALSE     27
28      TRUE     TRUE CTCF_only            TRUE   TRUE    TRUE     28
29      TRUE    FALSE prom                 TRUE   TRUE    TRUE     29
30      TRUE     TRUE prom                 TRUE   TRUE    TRUE     30
⋮      ⋮        ⋮     ⋮                   ⋮      ⋮       ⋮         ⋮
177052 FALSE    FALSE other_nonTSS         TRUE  FALSE    TRUE     177052
177053 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177053
177054 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177054
177055 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177055
177056 FALSE    FALSE other_nonTSS        FALSE   TRUE   FALSE     177056
177057 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177057
177058 FALSE    FALSE other_nonTSS        FALSE   TRUE    TRUE     177058
177059 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177059
177060 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177060
177061 FALSE    FALSE other_nonTSS         TRUE  FALSE    TRUE     177061
177062 FALSE    FALSE other_TSS            TRUE   TRUE    TRUE     177062
177063 FALSE    FALSE other_nonTSS         TRUE  FALSE   FALSE     177063
177064 FALSE     TRUE CTCF_only            TRUE   TRUE    TRUE     177064
177065 FALSE    FALSE other_nonTSS        FALSE   TRUE    TRUE     177065
177066 FALSE    FALSE other_nonTSS        FALSE   TRUE    TRUE     177066
177067 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177067
177068 FALSE    FALSE prom                 TRUE   TRUE    TRUE     177068
177069 FALSE    FALSE other_TSS           FALSE  FALSE    TRUE     177069
177070 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177070
177071 FALSE    FALSE other_nonTSS         TRUE   TRUE    TRUE     177071
177072 FALSE    FALSE other_nonTSS         TRUE  FALSE   FALSE     177072
177073 FALSE    FALSE other_nonTSS         TRUE  FALSE    TRUE     177073
177074 FALSE     TRUE CTCF_only           FALSE   TRUE    TRUE     177074
177075 FALSE     TRUE other_TSS           FALSE  FALSE    TRUE     177075
177076 FALSE    FALSE other_nonTSS         TRUE  FALSE   FALSE     177076
177077 FALSE    FALSE poised_enh           TRUE   TRUE    TRUE     177077
177078 FALSE    FALSE prom                 TRUE   TRUE    TRUE     177078
177079 FALSE    FALSE prom                 TRUE   TRUE    TRUE     177079
177080 FALSE    FALSE prom                 TRUE   TRUE    TRUE     177080
177081 FALSE    FALSE other_nonTSS        FALSE   TRUE    TRUE     177081